name: swiftcel
description: "Parcel Delivery App."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.3.0
  google_maps_flutter: ^2.18.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0
  shared_preferences: ^2.5.5
  provider: ^6.1.5+1
  firebase_core: ^4.13.0
  firebase_analytics: ^12.4.6
  fl_chart: ^1.2.0
  app_links: ^7.0.0
  google_places_flutter: ^2.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/orange logo only.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FF6B35"
  adaptive_icon_foreground: "assets/icons/white transparent logo only.png"  # transparent truck only


flutter_native_splash:
  color: "#FF6B35"                               # same orange, as splash background
  image: "assets/icons/white transparent logo only.png"   # same transparent truck

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700