// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK35n2RGZfI-DL6gz_rp5QC3OBazhZ_J8',
    appId: '1:335824276054:web:3414e78cd49b4f4993c9f7',
    messagingSenderId: '335824276054',
    projectId: 'swiftcel0',
    authDomain: 'swiftcel0.firebaseapp.com',
    storageBucket: 'swiftcel0.firebasestorage.app',
    measurementId: 'G-HG1VG9VN2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxoKNnpaiCtl3aimv428vYoN1K5HySa2w',
    appId: '1:335824276054:android:e5b4525633a6fe4e93c9f7',
    messagingSenderId: '335824276054',
    projectId: 'swiftcel0',
    storageBucket: 'swiftcel0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhxymoxSJw76cq6rj0neuyBNtCyOVp9ek',
    appId: '1:335824276054:ios:564a1eef52cf972a93c9f7',
    messagingSenderId: '335824276054',
    projectId: 'swiftcel0',
    storageBucket: 'swiftcel0.firebasestorage.app',
    iosBundleId: 'com.example.swiftcel',
  );
}
